projects/client/client/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('admin/', views.admin ),
    path('', views.index),
    path('services/', views.service),
    path('team/', views.team),
    path('portfolio/', views.portfolio),
    path('create',views.createProduct),
    path('list/',views.listProducts),
    path('list/view/<int:id>',views.viewProduct),
    path('list/delete/<int:id>',views.deleteProduct),
    path('list/edit/<int:id>',views.editProduct),
]

projects/client/client/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Products(models.Model):
    title = models.CharField(max_length=255)
    discription = models.TextField()
    price = models.CharField(max_length=10)
    quantity = models.CharField(max_length=10)
    image = models.FileField(upload_to='static/client/img/uploads/')
    status = models.CharField(max_length=1,default="0")
    created = models.DateTimeField(auto_now_add=True,null=True)
    modified = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        managed = False
        db_table = 'products'


class Services(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    status = models.CharField(max_length=1,default="0")
    created = models.DateTimeField(auto_now_add=True,null=True)
    modified = models.DateTimeField(auto_now=True,null=True)

    class Meta:
        managed = False
        db_table = 'services'

projects/client/templates/client/admin/product/create.html
{% extends 'client/admin/admin.html' %} 
{% block title %}Create Form {% endblock %}
{% block body %}
 
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Create post-form</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST" class="post-form" action="/create" enctype="multipart/form-data">
              {% csrf_token %}  
              <div class="box-body">
                    <div class="form-group">
                        <label for="">Title</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        {{ form.discription }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Price</label>
                        {{ form.price }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Quantity</label>
                        {{ form.quantity }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Image</label>
                        {{ form.image }}
                    </div>
                </div><!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div><!-- /.box -->
    </div><!--/.col (left) -->
    <!-- right column -->
  </div>
{% endblock %}

projects/client/templates/client/admin/product/edit.html
{% extends 'client/admin/admin.html' %} 
{% block title %}Edit Form {% endblock %}
{% block body %}

<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Edit post-form</h3>
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST" class="post-form" action="/list/edit/{{product.id}}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="box-body">
                    <div class="form-group">
                        <label for="">Title</label>
                        <input type="text" name="title" maxlength="255" value="{{product.title}}" class="form-control" id="id_title">
                    </div>
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="discription" cols="40" rows="10" class="form-control"
                            id="id_discription">
                            {{product.discription}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Price</label>
                        <input type="text" name="price" maxlength="10" value="{{product.price}}" class="form-control" id="id_price">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Quantity</label>
                        <input type="text" name="quantity" maxlength="10" value="{{product.quantity}}" class="form-control" id="id_quantity">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Image</label>
                        <input type="file" name="image" value="{{product.image}}" id="id_image">
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div><!-- /.box -->
    </div>
    <!--/.col (left) -->
    <!-- right column -->
</div>
{% endblock %}

projects/client/templates/client/admin/product/list.html
{% extends 'client/admin/admin.html' %} 
{% block title %} Product List {% endblock %}
{% block body %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Quantity
            </th>
            <th>
                Image
            </th>
            <th>
                Preview
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    
    <tbody>
            {% for product in products %}
        <tr>
            <td>
                {{product.title}}
            </td>
            <td>
                {{product.price}}
            </td>
            <td>
                {{product.quantity}}
            </td>
            <td>
                {{product.image}}
            </td>
            <td>
                <img src="/{{product.image}}" width="50" >
            </td>
            <td>
                <a class="btn btn-info" title="Edit" href="edit/{{product.id}}"><span class="fa fa-edit"></span></a>
                <a class="btn btn-success" title="View" href="view/{{product.id}}"><span class="fa fa-eye"></span></a>
                <a class="btn btn-danger" title="Delete" href="delete/{{product.id}}"><span class="fa fa-trash-o"></span></a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

projects/client/templates/client/admin/product/view.html
{% extends 'client/admin/admin.html' %} 
{% block title %} Product List {% endblock %}
{% block body %}
<div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">Product view</div>
      <div class="panel-body">
        {{product.title}}
        {{product.price}}
        {{product.quantity}}
      </div>
      <div class="panel-footer">
          <a class="btn btn-info" href="/list">Back</a>
      </div>
    </div>
  </div>

    
{% endblock %}